include(${SOURCE_SDK_DIRECTORY_CMAKE}/libraries/tier0.cmake)
include(${SOURCE_SDK_DIRECTORY_CMAKE}/libraries/tier2.cmake)
include(${SOURCE_SDK_DIRECTORY_CMAKE}/libraries/tier3.cmake)
include(${SOURCE_SDK_DIRECTORY_CMAKE}/libraries/appframework.cmake)
include(${SOURCE_SDK_DIRECTORY_CMAKE}/libraries/bitmap.cmake)
include(${SOURCE_SDK_DIRECTORY_CMAKE}/libraries/vstdlib.cmake)
